name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for git-cliff

      - name: Install git-cliff
        run: |
          wget -qO- https://github.com/orhun/git-cliff/releases/latest/download/git-cliff-$(uname -m)-unknown-linux-musl.tar.gz | tar -xz -C /tmp
          sudo mv /tmp/git-cliff-$(uname -m)-unknown-linux-musl/git-cliff /usr/local/bin/

      - name: Update CHANGELOG
        run: |
          git-cliff --latest --tag ${{ github.ref_name }} --output CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG for ${{ github.ref_name }}" || exit 0
          git push

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
